### PR TITLE
Use Observable.using in CreateObservable.from(Path)/listFolder

### PR DESCRIPTION
**Pull request by samuelgruetter**
A suggestion on how to avoid exception-handling boilerplate code

### CODE REVIEW

**Comment by meddle0x53** [comment]
Very good suggestion. Only one problem - these methods are used in the chapters before 8, and chapter 8 introduces the 'using' method. So... Maybe we should keep the old versions of the methods. I know that most of the methods are implemented in very naive fashion, but I think it is necessary, actually chapter 8 will show how we can do create HTTP request Observable with 'using'.
What do you think?

**Comment by meddle0x53** [comment]
Or maybe the naive examples should be in the book, and more sophisticated ones could be in the source code with the proper comments - so if the reader decides to go deeper, he/she will have something better to play with. What about that?

**Comment by samuelgruetter** [comment]
An important skill that the readers should have or acquire is to be able to read and understand APIs, and to use them without understanding every implementation detail.
This place would be a good opportunity to "train" the readers on that: Only print the signature and some javadoc for the `listFolder` and `from(Path)` methods, and say that you'll explain in chapter 8 how to implement them. Since the readers can use this repo, they'll be able to run the code without understanding the `using` method.
It makes even more sense given that the section in question is about `flatMap`, because the resource management and error handling really have nothing to do with the `flatMap` that you want to explain.

**Comment by samuelgruetter** [comment]
> I know that most of the methods are implemented in very naive fashion, but I think it is necessary,

You should try to avoid as much as possible printing these naive implementations in the book, because they will engrave in your readers' memories, and they will continue to write such code...
Putting things they don't yet understand into a small library, as suggested above, is one way to achieve it, another is to choose examples which do not require complex machinery to get the needed Observables.
I understand avoiding these naive examples is not easy, but you should really try hard to achieve as much as possible.

**Pull request merged**
